
```{r setup}
list.of.packages <- c("stringr", "knitr", "RTextTools", "data.table")
new.packages <- list.of.packages[!(list.of.packages %in% installed.packages()[,"Package"])]
if(length(new.packages)) install.packages(new.packages)
lapply(list.of.packages, require, character.only = TRUE)
rm(list.of.packages, new.packages)

opts_chunk$set(echo=TRUE,
               cache=TRUE, autodep=TRUE,
               message=FALSE, warning=FALSE)
options(scipen = 1, digits = 4)
```

```{r}
clean_text = function(text){
  text = str_replace_all(text, pattern='\n', replacement=' ')
  text = tolower(str_replace_all(text, '[^[A-Za-z ][:space:]]', replacement=' '))
  return(text)
}
```

```{r}
train = fread("data/train.csv")
train$comment_text = clean_text(train$comment_text)
label.names = colnames(train)[3:8]
```

```{r}
model.fnames = paste0('models/', label.names, '_svm_model.r')
doc_term_matrix.fnames = paste0('doc_term_matrices/', label.names, '_dtm.r')

#Get the docterm.matrix and train the model.
for(i in 1:length(model.fnames)){
  model.fname = model.fnames[i]
  doc_term_matrix.fname = doc_term_matrix.fnames[i]
  if(!file.exists(model.fname)){
    label.name = gsub('models/', '', gsub('_svm.*$', '', model.fname))
    print(paste0('sampling ', label.name))
    labels = train[[label.name]]
    
    SAMPLE.SIZE = 15000
    PROPORTION.TRAIN = 0.8
    ntrain = floor(SAMPLE.SIZE*PROPORTION.TRAIN)
    ntest = SAMPLE.SIZE - ntrain
    
    yes_label_indices = sample(which(labels==1))
    n_yes = length(yes_label_indices)
    n_yes.draw = ifelse(ceiling(SAMPLE.SIZE/2) < n_yes, ceiling(SAMPLE.SIZE/2), n_yes)
    n_yes.train = floor(n_yes.draw * PROPORTION.TRAIN)
    n_yes.test = floor(n_yes.draw * (1-PROPORTION.TRAIN))
    train_indices = yes_label_indices[1:n_yes.train]
    test_indices = yes_label_indices[(n_yes.train+1):(n_yes.train + n_yes.test)]
    
    no_label_indices = sample(which(labels==0))
    cutoff = ntrain - length(train_indices)
    train_indices = c(train_indices, no_label_indices[1:cutoff])
    no_label_indices = no_label_indices[(cutoff+1):length(no_label_indices)]
    cutoff = ntest - length(test_indices)
    test_indices = c(test_indices, no_label_indices[1:cutoff])
    
    model_subset = train[c(train_indices, test_indices)]
    labels=model_subset[[label.name]]
    print(paste0('making docterm matrix and container for ', label.name))
    docterm.matrix = create_matrix(model_subset$comment_text, removeSparseTerms=.999)
    container = create_container(docterm.matrix, labels=labels, trainSize = 1:ntrain, 
                                 testSize = (ntrain+1):(ntrain+ntest), virgin=FALSE)
    
    print(paste0('training ', label.name))
    model = train_models(container, algorithms=c("SVM"), kernel="linear", cost=1)
    save(docter.matrix, file=doc_term_matrix.fname)
    save(model, file=model.fname)
  }
}
```

```{r}
testdata = fread('data/test.csv')
testdata$comment_text = clean_text(testdata$comment_text)
#testdata = testdata[1:5000,]
testdata.splitted = split(testdata, (seq(nrow(testdata))-1) %/% 1000) 
rm(testdata)

#trace("create_matrix", edit=T) #'Acronym' -> 'acronym'

probs = vector(mode='list', length=length(label.names))
names(probs) = label.names
for(i in 1:length(models)){
  print(label.names[i])
  model = models[[i]]
  chunk_probs = vector(mode='list', length=length(testdata.splitted))
  for(j in 1:length(testdata.splitted)){
    print(j)
    testdata.chunk = testdata.splitted[[j]]
    pred.matrix = create_matrix(testdata.chunk$comment_text, originalMatrix=docterm.matrix)
    predSize = nrow(testdata.chunk);
    predContainer = create_container(pred.matrix, rep(0,predSize), testSize=1:predSize, virgin=FALSE)
    results = classify_models(predContainer, model)
    chunk_probs[[j]] = ifelse(results$SVM_LABEL==1, results$SVM_PROB, 1-results$SVM_PROB)
  }
  final_result = data.frame(unlist(chunk_probs))
  colnames(final_result) = c('prob')
  write.table(final_result, file=paste0(label.names[i], '_results.csv'), quote=FALSE, sep=',', row.names=FALSE))
  probs[[i]] = unlist(chunk_probs)
}
```

```{r}
allprobs = as.data.table(do.call(cbind, probs))
allprobs$id = data$id[1:5000]
setcolorder(allprobs, c('id', label.names))
allprobs = allprobs[,c('id', label.names)]
write.table(allprobs, file='all_results_first5000.csv', quote=FALSE, sep=',', row.names=FALSE)
```


